config-version = 1
# The player can only be synced to ONE forge server at a time.
# Resync will always happen if the player isn't synced to any server and is switching to a forge server.
[ReSync]
# In seconds. How much time the player has to reconnect before the resync cancels.
resync-timeout = 30

# Possible values: "Always", "Never".
# Always: Always kicks the player while switching servers. The safest.
# Never: Switches server without kicking/resyncing the player. Can cause client crashes depending on the mods.

# When the player is connecting to a forge server while being synced to another.
# Default: "always"
resync-forge-to-forge = "always"
# When the player is connecting to a vanilla server and is synced to a forge server.
# Default "never". "always" not recommended for servers with vanilla hubs/lobbies.
unsync-forge-to-vanilla = "never"

# Maybe you want to have one 1.16.5 modpack-server and one 1.18.2 modpack-server behind Velocity, in order for Ambassador to tell the
# diffrence between modpacks on the connecting client, the plugin looks at the client's protocol version.

# You may add more diffrentiators, just make sure they have diffrent protocol versions.
[Differentiators]

# Protocol version - 1.18.2
[Differentiators.758]
# The server that players will initially sync to when connecting to the proxy.
# When left empty; Players will be able to join but will need to resync when joining connecting to a forge server.
# The name should be the same as specified in the "velocity.toml" config, e.g. "lobby".
default-forge-server = ""

# Some modpacks are not compatible with vanilla servers.
# To make sure they don't get connected to one upon login (like a vanilla lobby), change this to true.
forced = false

# Protocol version - 1.16.5
[Differentiators.754]
default-forge-server = ""
forced = false